name: Build and Push MCP Server

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Version of the MCP server image to build'
        type: string
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.PORT_MACHINE_USER_ID }}
          password: ${{ secrets.PORT_MACHINE_USER_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ghcr.io/port-labs/port-mcp-server:${{ inputs.VERSION }}
            ghcr.io/port-labs/port-mcp-server:latest

